FLOWSHEET:
  flowsheet:
    name: Flowsheet
  streams:
    Feed:
      node_in: 0
      node_out: 1
    Coarse:
      node_in: 1
      node_out: 2
    Fine:
      node_in: 1
      node_out: 3
  nodes:
    0:
      name: feed
      subset: 0
    1:
      name: screen
      subset: 0
    2:
      name: lump
      subset: -1
    3:
      name: fines
      subset: 1